### ISSUE TITLE
Can not install akvmod in Linux Mint 19

### ISSUE THREAD

**Issue by hexusdev** [webcamoid/akvcam#9] opened 2020-02-13 08:18 UTC
After executing **sudo make install** I get the error:

```
➜  src git:(master) sudo make install
make -C /lib/modules/5.3.0-28-generic/build M=/home/dev15/akvcam/src modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-28-generic'
  INSTALL /home/dev15/akvcam/src/akvcam.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.3.0-28-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-28-generic'
```

and this command **sudo insmod akvcam.ko** leads to this:
`insmod: ERROR: could not insert module akvcam.ko: Operation not permitted`

**Comment by hipersayanX** [comment] 2020-02-13 12:36
This question has been already answered and solved [here](https://github.com/webcamoid/akvcam/issues/4#issuecomment-495031977). Closing as duplicate of #4.

**Closed as completed by hipersayanX** 2020-02-13 12:36 UTC
Labels: Verdict: Duplicate
