### ISSUE TITLE
will not install Linux Mint 19.3

### ISSUE THREAD

**Issue by jrenshaw1972** [webcamoid/akvcam#8] opened 2020-02-02 01:16 UTC
make -C /lib/modules/5.3.0-28-generic/build M=/home/jeff/Downloads/akvcam-master/src modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-28-generic'
  INSTALL /home/jeff/Downloads/akvcam-master/src/akvcam.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.3.0-28-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-28-generic'

I installed libelf-dev and using sudo depmod -a doen't make a difference, still get the same results

**Comment by hipersayanX** [comment] 2020-02-04 20:39
This question has been already answered and solved [here](https://github.com/webcamoid/akvcam/issues/4#issuecomment-495031977). Closing as duplicate of #4.

**Closed as completed by hipersayanX** 2020-02-04 20:39 UTC
Labels: Verdict: Duplicate
